name: flutter_quantos_widgets
description: A collection of useful Flutter widgets

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_throttling: ^1.0.1
    #git: https://github.com/quantosapplications/throttling.git
  tuple: ^2.0.0-nullsafety.0
  pedantic: ^1.11.0

  # state management
  provider: ^5.0.0-nullsafety.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true